apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcce-g1

resources:
- ../../base
- rabbitmq-secret.yaml

configMapGenerator:
- name: app-config
  literals:
  - ENVIRONMENT=prod
