apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcce-g1-prod

resources:
- namespace.yaml
- ../../base
- rabbitmq-secret.yaml

patches:
- path: patches/service-ports.yaml

configMapGenerator:
- name: app-config
  literals:
  - ENVIRONMENT=prod
  - RABBITMQ_HOST=rabbitmq.mcce-g1-prod
  - RABBITMQ_PORT=5673
