apiVersion: batch/v1
kind: CronJob
metadata:
  name: rabbitmq-producer
spec:
  schedule: "*/1 * * * *"  # Run every minute
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: producer
            image: ghcr.io/mcce2024/akkt1-g1-producer:latest
            env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          restartPolicy: OnFailure 