apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: mcce-g1
type: Opaque
# To create the actual secret:
# 1. Copy this file to rabbitmq-secret.yaml
# 2. Replace placeholders with base64 encoded values:
#    echo -n "your-username" | base64
#    echo -n "your-password" | base64
data:
  username: <BASE64_ENCODED_USERNAME>
  password: <BASE64_ENCODED_PASSWORD> 