apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
    serviceAccount: consumer-sa
  annotations:
    security.kubernetes.io/owner: "MCCE-G1"
    security.kubernetes.io/environment: "production"
spec:
  selector:
    app: consumer
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  type: LoadBalancer
